Add support for normalization options
sindresorhus/compare-urls pull request #1
Opened 2016-09-26 13:44 UTC by varunkumar

2016-09-26 13:48 UTC, SamVerschueren commented on index.js
> +	return normalizeUrl(a, opts) === normalizeUrl(b, opts);
Just pass through the `options` object directly. `normalizeUrl` already [copies](https://github.com/sindresorhus/normalize-url/blob/master/index.js#L36) the object.

2016-09-26 13:48 UTC, SamVerschueren requested changes

2016-09-26 13:48 UTC, SamVerschueren commented
Maybe also add an API section in the readme.

2016-10-22 22:43 UTC, sindresorhus commented
Closing for lack of response.

2016-10-22 22:43 UTC, closed without merging